// @flow

export const INIT_PROJECTS = 'INIT_PROJECTS'
export const INIT_ACTIONS = 'INIT_ACTIONS'
export const INIT_CURRENT_PROJECT = 'INIT_CURRENT_PROJECT'
export const INIT_CURRENT_ACTION = 'INIT_CURRENT_ACTION'
export const INIT_CURRENT_NOTE = 'INIT_CURRENT_NOTE'
export const INIT_NOTES = 'INIT_NOTES_ABOUT_CURRENT_PROJECT'
export const INIT_RECORDS = 'INIT_RECORDS'
export const INIT_QUERY_RECORDS = 'INIT_QUERY_RECORDS'
export const INIT_PROJECT_SELECTOR_TARGET = 'INIT_PROJECT_SELECTOR_TARGET'
export const INIT_ACTION_SELECTOR_TARGET = 'INIT_ACTION_SELECTOR_TARGET'
export const INIT_NOTE_SELECTOR_TARGET = 'INIT_NOTE_SELECTOR_TARGET'